import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StatusIndicator from "@/components/StatusIndicator";
import HistoryManager from "@/components/HistoryManager";
import ThemeManager from "@/components/ThemeManager";
import ActivityManager from "@/components/ActivityManager";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <StatusIndicator />
        <HistoryManager />
        <ThemeManager />
        <ActivityManager />
      </body>
    </html>
  );
}
